import 'package:flutter/material.dart';

Color green = const Color(0xFF029933);

List<String> themes = const [
  "Tawhid",
  "Prière",
  "Ramadan",
  "Zakat",
  "Hajj",
  "Le Coran",
  "La Sunna",
  "Prophètes",
  "73 Sectes",
  "Compagnons",
  "Les Savants",
  "Les innovations",
  "La mort",
  "La tombe",
  "Le jour dernier",
  "Les 4 Imams",
  "Les Anges",
  "Les Djinns",
  "Les gens du livre",
  "99 Noms",
  "Femmes",
  "Voyage",
  "Signes",
  "Adkars",
];

List<String> scholars = const [
  "Cheikh Abdesamad Karoum / الشيخ عبد الصمد كروم",
  "Cheikh Abderrazak Al Badr / الشيخ عبد الرزاق البدر",
  "Cheikh Abdelkarim Al Khoudayr / الشيخ عبد الكريم الخضير",
  "Cheikh Abdelmadjid Jumu’a / الشيخ عبد المجيد جمعة",
  "Cheikh Abdelmouhsin Al Abbad Al Badr / الشيخ عبد المحسن العباد البدر",
  "Cheikh Abdellah Al Idrissi / شيخ عبدالله الدراسي",
  "Cheikh Abdellah Al Qussayir / شيخ عبد الله القصير",
  "Cheikh Abdallah Al Ghoudayan / الشيخ عبد الله الغديان",
  "Cheikh Abderahman As-Sa’di / الشيخ عبد الرحمن السعدي",
  "Cheikh Abderahman Mouhyiddine / الشيخ عبد الرحمن محي الدين",
  "Cheikh Abdesalam Ibn Barjas / الشيخ عبد السلام بن برجس",
  "Cheikh Abdesalam Chouway’ir / الشيخ عبد السلام الشويعر",
  "Cheikh Ahmad Bazmoul / الشيخ أحمد بزمول",
  "Cheikh Ahmad Najmi / الشيخ أحمد النجمي",
  "Cheikh Al Albani / الشيخ الألباني",
  "Cheikh Al Uthaymin / شيخ العثيمين",
  "Cheikh Ali Cheikh / شيخ علي شيخ",
  "Cheikh Ali Ramli / الشيخ علي الرملي",
  "Cheikh As Souhaymi / شيخ السحيمي",
  "Cheikh Aziz bin Farhan Al Anizi / الشيخ عزيز بن فرحان العنزي",
  "Cheikh Faleh Mundakar / شيخ فلح مندكار",
  "Cheikh Faqiri / شيخ فقيري",
  "Cheikh Ferkous / الشيخ فركوس",
  "Cheikh Foued Ibn Saoud Al Amri / الشيخ فؤاد بن سعود العمري",
  "Cheikh Hassan Ibn Abdelwahhab Al Bana / الشيخ حسن بن عبد الوهاب البنا",
  "Cheikh Ibrahim Al Mouhaymid / الشيخ إبراهيم المحيميد",
  "Cheikh Ibn Baz / الشيخ ابن باز",
  "Cheikh Mouqbil Al Wadi’i / الشيخ مقبل الوادعي",
  "Cheikh Muhammad Al Aqil / الشيخ محمد العقيل",
  "Cheikh Muhammad Al Fifi / الشيخ محمد الفيفي",
  "Cheikh Muhammad Al Jami / الشيخ محمد الجامي",
  "Cheikh Muhammad Al Shanqiti / الشيخ محمد الشنقيطي",
  "Cheikh Muhammad Al Wussabi / الشيخ محمد الوصابي",
  "Cheikh Muhammad Bazmoul / الشيخ محمد بزمول",
  "Cheikh Muhammad Ibn Hadi Al Madkhali / الشيخ محمد بن هادي المدخلي",
  "Cheikh Muhammad Ibn Ibrahim / الشيخ محمد بن إبراهيم",
  "Cheikh Muhammad Shawkani / الشيخ محمد الشوكاني",
  "Cheikh Mohamed Ghaïth / شيخ محمد غيث",
  "Cheikh Rabi’ Al Madkhali / الشيخ ربيع المدخلي",
  "Cheikh Ramzan Al Hadjiri / الشيخ رمضان الحجيري",
  "Cheikh Raslan / شيخ عسلان",
  "Cheikh Rouhayli (Souleyman) / شيخ سليمان الرحيلي",
  "Cheikh Saad Ibn Nasser Ash Shathry / الشيخ سعد بن ناصر الشثرى",
  "Cheikh Salih Al Fawzan / الشيخ صالح الفوزان",
  "Cheikh Salih Al Louhaydan / الشيخ صالح اللحيدان",
  "Cheikh Salih Al Osaymi / الشيخ صالح العصيمي",
  "Cheikh Salih Al Shaykh / الشيخ صالح الشيخ",
  "Cheikh Salih Ali Cheikh / شيخ صالح علي شيخ",
  "Cheikh Salih Souhaymi / الشيخ صالح السحيمي",
  "Cheikh Salih Sindi / شيخ صالح سندي",
  "Cheikh Salmane At Tawil / شيخ سلمان الطويلة",
  "Cheikh Tal’at Zahran / الشيخ طلعت زهران",
  "Cheikh Ussamah Ibn Saoud Al Amri / الشيخ أسامة بن سعود العمري",
  "Cheikh Wassiyullah Al Abbas / الشيخ وصي الله عباس",
  "Cheikh Zayd Al Madkhali / الشيخ زيد المدخلي",
];

List<String> imams = [
  "Cheikh Djily Cheikh Abou Maymouna / الشيخ جيلي شيخ أبو ميمونة",
  "Cheikh Ismaïl Ibn Hādī / الشيخ اسماعيل بن هادي",
  "Cheikh Mehdi Ben naceur / الشيخ مهدي بن ناصر",
  "Cheikh Samy Philippe Chaouche / الشيخ سامي بن عبد الكريم الشاوش",
  "Cheikh Tahir Abu Sany / الشيخ طاهر أبو سني",
];

List<String> services_titles = [
  "Service 1 : Location voitures Maroc 🇲🇦",
  "Service 2 : Développement applications",
  "Service 3 : Produit naturels",
  "Service 4 : Vêtements pour femme",
  "Service 5 : Omra",
  "Service 6 : Boutique en ligne",
  "Service 7 : Montres",
];

List<String> services_links = [
  "http://onelink.to/5n88za",
  "Contacter sur WhatsApp",
  "https://monjardinprophetique.com",
  "https://www.anaqacollection.fr",
  "https://omraprivee.com",
  "https://www.maktaba-abou-daoud.fr",
  "https://al-almass.com",
];

List<String> services_images = [
  'assets/images/services/s1.jpg',
  'assets/images/services/s2.jpg',
  'assets/images/services/s3.jpg',
  'assets/images/services/s4.jpg',
  'assets/images/services/s5.jpg',
  'assets/images/services/s6.jpg',
  'assets/images/services/s7.jpg',
]
;
